### ISSUE TITLE
Source code for modding?

### ISSUE THREAD

**Issue by Spectral-Dreams** [Joshhhuaaa/EnhancedSCDAOnline#3]
do you have the "source code" or whatever it's called for your enhanced DA? I'd like to make some changes to the game and poke around the files (if such a thing is possible).

If you don't wanna share the source code, then maybe instructions on how to decompile/recompile the game files for modding purposes.

Thanks.

**Comment by Joshhhuaaa** [comment]
There is no publicly available source code for these games. All modifications to Enhanced SCDA Online were made solely through hex editing the files. The included script that caps the framerate during loading screens was added by ThirteenAG's SCDA Online code [here](https://github.com/ThirteenAG/WidescreenFixesPack/commit/b9d8e8ec8aa4f94d2841a9f3ef6660740fe8a08d).
