### ISSUE TITLE
Filling A Custom Lobby with Bots only fills the Mercs/Upsilon Side of the bots, whilst the Spy side stays empty

### ISSUE THREAD

**Issue by Mahim2000** [Joshhhuaaa/EnhancedSCDAOnline#4]
Taking the Mercs side doesnt spawn any Spies,
and Taking the Spies side doesnt spawn any teammates.

**Comment by Joshhhuaaa** [comment]
This is the original game’s behavior. Ubisoft never developed bot support for spies.

**Comment by Mahim2000** [comment]
Will the bot support be properly implemented in the future? If yes, how much is the possibility?
