### ISSUE TITLE
Ultrawide Aspect Ratios Cut-Off HUD Elements

### ISSUE THREAD

**Issue by MamaKrama** [Joshhhuaaa/EnhancedSCDAOnline#5]
When running an ultrawide monitor (3440x1440 in this case), the client defaults to the 3840x2160 in-game resolution which cuts off the in-game timer, chat messages, and screws up the map area text overlay. Could be fixed with a scaling option for the in-game HUD or add in-game support for 21:9 aspect ratios. Editing HudParams.ini does not affect anything in-game nor does the HUD scale option in Default.ini.

**Comment by Joshhhuaaa** [comment]
Yeah that's to be expected, I would just play on 2560x1440 on your display instead since the game supports 16:9 natively. I personally wouldn't be able to make a 21:9 patch for the HUD, maybe someone in the future could be interested in it.
